// UI builders take many GPUI inputs by design and guard `self.live` with
// `is_some()` before `expect`; these structural lints are allowed UI-wide.
#![allow(
    clippy::too_many_arguments,
    clippy::type_complexity,
    clippy::unnecessary_unwrap
)]

mod account_lifecycle;
mod accounts;
mod anim_layer;
mod app_slice;
mod appearance;
mod auth_recovery;
mod bidi_line;
mod chat_theme;
mod clipboard_files;
mod composer_rtl;
mod composer_thumb;
mod editor_art;
mod esc_stack;
mod ffmpeg_video;
mod force_reply;
mod frame_clock;
mod image_budget;
mod inline_video;
mod lru;
mod motion;
mod native_video;
mod photo_edit;
mod photo_editor;
mod pin_box;
mod presence;
mod privacy;
mod privacy_extra;
mod rtl_demo;
mod selectable_text;
mod selection_mode;
mod sessions_extra;
mod shortcut_pack;
mod story_areas;
mod synthetic;
mod updates;
mod vanish;

pub(crate) use account_lifecycle::*;
pub(crate) use accounts::*;
pub(crate) use chat_theme::*;
pub(crate) use privacy::{PrivacyEditorTarget, PrivacyExceptionKind, apply_ready_privacy};

mod dialogs;

pub(crate) use dialogs::*;
mod format_helpers;
mod history_fx;
mod history_row;
mod keybindings;
mod menu_states;
mod playback;
mod player_bar;

pub(crate) use format_helpers::*;
pub(crate) use history_row::*;
pub(crate) use keybindings::*;
pub(crate) use menu_states::*;
pub(crate) use playback::*;
mod story_page;

pub(crate) use story_page::{StoryPage, apply_ready_story_albums};

mod actions;
mod activity_indicator;
mod app;
mod app_demo;
mod app_render;
mod archive_row;
mod audio;
mod audio_playback;
mod auth_registration;
mod auth_ui;
mod bot_pending;
mod bot_stream;
mod bots;
mod bubble_header;
mod bubble_header_demo;
mod call_panel;
mod call_sounds;
mod call_tones;
mod call_ui;
mod calls;
mod capture_access;
mod capture_block;
mod chat;
mod chat_bars;
mod chat_list;
mod chat_look_demo;
mod chat_look_ui;
mod chat_row;
mod chat_swipe_ui;
mod chatlist_demo;
mod chatlist_style;
mod checklists;
mod composer;
mod composer_shortcuts;
mod composer_suggest;
mod composer_ui;
mod connect_ui;
mod contacts;
mod conversation;
mod custom_keyboard;
mod deep_link_routes;
mod deep_links;
mod demo;
mod demo_setup;
mod demo_stream;
mod downloads;
mod drafts;
mod emoji_sets;
mod entity_links;
mod event_log;
mod find_demo;
mod folder_demo;
mod folder_demo_followups;
mod folder_extras;
mod folder_glyphs;
mod folder_share;
mod folder_tabs;
mod folders;
mod forum_extras;
mod forums_saved_demo;
mod forward;
mod gifs_ui;
mod group_admin_panels;
mod group_admin_settings;
mod group_admin_settings_demo;
mod group_call_extras;
mod group_call_panel;
mod group_call_tiles;
mod group_call_ui;
mod group_calls;
mod group_invites;
mod group_members;
mod group_moderation;
mod group_panels;
mod groups;
mod groups_forum;
mod groups_welcome;
mod history;
mod inline_mode;
mod inline_playback;
mod invite_admin_ui;
mod jump_buttons;
mod jump_date;
mod keyboard_demo;
mod marketplace;
mod media_panel;
mod media_viewer;
mod member_moderation;
mod member_moderation_demo;
mod message_actions;
mod message_checklist;
mod message_games;
mod message_media;
mod message_menu_demo;
mod message_menu_ui;
mod message_payments;
mod message_poll;
mod message_text;
mod navigation;
mod notification_settings;
mod notifications;
mod onboarding;
mod ownership;
mod passcode;
mod payments;
mod polls;
mod premium_demo;
mod premium_ui;
mod pressable;
mod profile;
mod profile_modal;
mod profile_panels;
mod profile_panels_demo;
mod proxy;
mod reactions;
mod recording;
mod rendering_demo;
mod request_share;
mod round_record;
mod round_seek;
mod saved_sublists;
mod scheduled;
mod scheduled_demo;
mod screenshot_demo;
mod search_ui;
mod secret_chats;
mod security;
mod security_recovery;
mod send_button_ui;
mod service_demo;
mod service_row;
mod settings_ui;
mod share_box_ui;
mod share_content_ui;
mod share_demo;
mod shared_media;
mod shell;
mod shortcuts;
mod showcase_demo;
mod signin_ui;
#[cfg(target_os = "macos")]
mod spellcheck_mac;
mod spellcheck_ui;
mod spoiler_fx;
mod sponsored;
mod statistics;
mod sticker_playback;
mod stickers_ui;
mod stories_strip_ui;
mod story_albums;
mod story_composer;
mod story_more;
mod story_ring;
mod story_viewer;
mod subsection_tabs;
mod system_unlock;
mod threads;
mod threads_demo;
mod translate_demo;
mod translate_ui;
mod video_pip;
mod viewer_demo;
mod wallpaper;
mod wallpaper_pattern;

pub use app::QuillApp;
pub use screenshot_demo::ScreenshotDemo;
pub use shell::{DialogKind, QuillShell};

mod device_qr;
