// UI builders take many GPUI inputs by design and guard `self.live` with
// `is_some()` before `expect`; these structural lints are allowed UI-wide.
#![allow(
    clippy::too_many_arguments,
    clippy::type_complexity,
    clippy::unnecessary_unwrap
)]

mod account_lifecycle;
mod account_state;
mod accounts;
mod admin_state;
mod anim_layer;
mod app_slice;
mod appearance;
mod appearance_power;
mod auth_recovery;
mod auth_state;
mod autoscroll_ui;
mod bidi_line;
mod bot_about;
mod bottom_action;
mod calls_state;
mod chat_list_state;
mod chat_theme;
mod clipboard_files;
mod composer_rtl;
mod composer_state;
mod composer_thumb;
mod connection_state;
mod demo_state;
mod dialogs_state;
mod editor_art;
mod esc_stack;
mod ffmpeg_video;
mod folders_state;
mod force_reply;
mod frame_clock;
mod frame_state;
mod group_call_state;
mod history_state;
mod image_budget;
mod inline_video;
pub(crate) mod interface_zoom;
mod links_state;
mod lru;
mod message_state;
mod motion;
mod native_video;
mod nested_click;
mod notify_state;
mod payments_state;
mod photo_edit;
mod photo_editor;
mod pickers_state;
mod pin_box;
mod playback_state;
mod presence;
mod privacy;
mod privacy_extra;
mod privacy_state;
mod recording_state;
mod search_state;
mod selectable_text;
mod selection_mode;
mod sessions_extra;
mod settings_state;
mod share_state;
mod shortcut_pack;
mod spell_state;
mod stories_state;
mod synthetic;
mod twofa_state;
mod updates;
mod updates_sync_ui;
mod vanish;
mod viewer_state;

pub(crate) use account_lifecycle::*;
pub(crate) use accounts::*;
pub(crate) use chat_theme::*;
pub(crate) use privacy::{PrivacyEditorTarget, PrivacyExceptionKind, apply_ready_privacy};

mod dialogs;

pub(crate) use dialogs::*;
mod format_helpers;
mod history_fx;
mod history_row;
mod keybindings;
mod menu_states;
mod playback;
mod player_bar;

pub(crate) use format_helpers::*;
pub(crate) use history_row::*;
pub(crate) use keybindings::*;
pub(crate) use menu_states::*;
pub(crate) use playback::*;
mod story_page;

pub(crate) use story_page::StoryPage;

mod actions;
mod activity_indicator;
mod app;
mod app_demo;
mod app_render;
mod archive_hint;
mod archive_row;
mod audio;
mod audio_playback;
mod auth_registration;
mod auth_ui;
mod bot_pending;
mod bot_stream;
mod bots;
mod bots_extras;
mod bubble_header;
mod call_audio_ui;
mod call_panel;
mod call_sounds;
mod call_tones;
mod call_ui;
mod calls;
mod calls_clear;
mod capture_access;
mod capture_block;
mod chat;
mod chat_bars;
mod chat_export_ui;
mod chat_list;
mod chat_look_ui;
mod chat_row;
mod chat_swipe_ui;
mod chatlist_global;
mod chatlist_style;
mod checklists;
mod composer;
mod composer_field;
#[cfg(all(test, feature = "demo-capture"))]
mod composer_field_tests;
mod composer_shortcuts;
mod composer_suggest;
mod composer_ui;
mod connect_ui;
mod contacts;
mod conversation;
mod custom_emoji_card;
mod custom_keyboard;
mod deep_link_routes;
mod deep_links;
mod demo;
mod demo_stream;
mod demos;
mod downloads;
mod drafts;
mod drop_zones;
mod emoji_sets;
mod entity_links;
mod event_log;
mod fact_check;
mod folder_extras;
mod folder_glyphs;
mod folder_picker_ui;
mod folder_share;
mod folder_tabs;
mod folders;
mod forum_extras;
mod forward;
mod gifs_ui;
mod group_admin_panels;
mod group_admin_settings;
mod group_call_extras;
mod group_call_members;
mod group_call_panel;
mod group_call_tiles;
mod group_call_ui;
mod group_calls;
mod group_invites;
mod group_links_boosts_ui;
mod group_members;
mod group_moderation;
mod group_panels;
mod groups;
mod groups_forum;
mod groups_welcome;
mod history;
mod inline_mode;
mod inline_playback;
mod invite_admin_more_ui;
mod invite_admin_ui;
mod jump_buttons;
mod jump_date;
mod link_info_boxes;
mod live_location_tick;
mod main_menu_extras;
mod marketplace;
mod media_panel;
mod media_viewer;
mod member_moderation;
mod message_actions;
mod message_checklist;
mod message_games;
mod message_media;
mod message_menu_ui;
mod message_payments;
mod message_poll;
mod message_text;
mod navigation;
mod notification_settings;
mod notifications;
mod onboarding;
mod ownership;
mod passcode;
mod payments;
mod polls;
mod premium_ui;
mod pressable;
mod profile;
mod profile_business;
mod profile_modal;
mod profile_panels;
mod proxy;
mod reactions;
mod recording;
mod reply_options_ui;
mod reply_pattern;
mod request_share;
mod round_record;
mod round_seek;
mod saved_sublists;
mod scheduled;
mod screenshot_demo;
mod search_ui;
mod secret_chats;
mod security;
mod security_recovery;
mod send_button_ui;
mod send_limits;
mod service_row;
mod settings_account_ui;
mod settings_phone_suggestion;
mod settings_ui;
mod share_box_ui;
mod share_content_ui;
mod shared_media;
mod shell;
mod shortcuts;
mod showcase_demo;
mod signin_ui;
mod spell_dictionaries;
#[cfg(target_os = "macos")]
mod spellcheck_mac;
mod spellcheck_ui;
mod spoiler_fx;
mod sponsored;
mod sponsored_about;
mod statistics;
mod sticker_playback;
mod stickers_ui;
mod stories_menu_ui;
mod stories_strip_ui;
mod story_albums;
mod story_composer;
mod story_insights_ui;
mod story_more;
mod story_ring;
mod story_viewer;
mod subsection_tabs;
mod suggestions_block;
mod system_unlock;
mod threads;
mod translate_ui;
mod video_pip;
mod wallpaper;
mod wallpaper_pattern;
mod web_app_tab;
mod web_app_ui;
mod window_chrome;
pub(crate) mod window_control;

pub use app::QuillApp;
pub use screenshot_demo::ScreenshotDemo;
pub use shell::{DialogKind, QuillShell};

mod device_qr;
