//! `Session::new`: the initial value of every reducer field.
use super::*;

impl Session {
    pub(crate) fn privacy_roundtrip_done(&mut self) {
        self.calls.privacy_pending = self.calls.privacy_pending.saturating_sub(1);
        if self.calls.privacy_pending == 0 {
            self.calls.privacy_loading = false;
            self.calls.privacy_error = false;
        }
    }

    pub fn new(account: AccountKey, diagnostics: Arc<dyn DiagnosticSink>) -> Self {
        let auth = AuthorizationState::WaitTdlibParameters;
        Self {
            account,
            account_generation: AccountGeneration(1),
            auth_view: view_for(&auth),
            auth,
            connection: ConnectionState::Initial,
            chats: HashMap::new(),
            main_order: Vec::new(),
            archive_order: Vec::new(),
            chat_list: ChatListState::new(),
            chats_state: ChatsState::new(),
            histories: HashMap::new(),
            stale_history_requests: HashSet::new(),
            revision: 0,
            mention_search: None,
            media_library: MediaLibrary::default(),
            message_reaction_options: None,
            active_reactions: Vec::new(),
            default_reaction: None,
            reaction_options_stale: false,
            message_menu_actions: None,
            message_report: None,
            message_audience: None,
            wanted_reactor_tab: None,
            sticker_set_view: None,
            custom_emoji_preview: None,
            emoji_pack_titles: HashMap::new(),
            message_action_note: None,
            groups: GroupsState::new(),
            message_link_result: None,
            message_link_public: false,
            message_caption_length_max: 1024,
            message_text_length_max: 4096,
            instant_view: None,
            instant_view_fallback_url: None,
            instant_view_urls: HashMap::new(),
            composer_preview: None,
            composer_preview_urls: HashMap::new(),
            message_link_error: None,
            ai_composer_text: None,
            ai_composer_blocks: None,
            ai_error: None,
            recognize_speech_error: None,
            resend_error: None,
            send_permission_error: None,
            flood_notice: None,
            scheduled_messages: Vec::new(),
            open_chat: None,
            app_active: true,
            settings: SettingsState::new(),
            sync: UpdatesSync::default(),
            auth_state: AuthState::new(),
            secret_chat_states: HashMap::new(),
            secret_chat_fetch_queue: Vec::new(),
            calls: CallsState::new(),
            support_user_ready: None,
            reply_targets: HashMap::new(),
            open_topic: None,
            pending_bot_messages: HashMap::new(),
            pending_bot_period_secs: 30,
            threads: ThreadsState::new(),
            poll_messages: HashMap::new(),
            view_generation: ViewGeneration(1),
            requests: RequestRegistry::default(),
            shutdown: ShutdownPhase::Running,
            last_seq: 0,
            in_flight_forward: None,
            queued_forward_flights: Vec::new(),
            share_search: ShareSearch::default(),
            last_forward: None,
            last_callback_answer: None,
            web_apps: WebApps::default(),
            last_login_url_info: None,
            login_url_request: None,
            payments: PaymentsState::new(),
            tone_limits: crate::message_menu::ToneLimits::default(),
            pending_force_reply: None,
            files: HashMap::new(),
            downloading: HashSet::new(),
            user_downloads: HashSet::new(),
            paused_downloads: HashSet::new(),
            failed_downloads: HashSet::new(),
            stalled_auto_downloads: HashSet::new(),
            open_chat_media_downloads: HashSet::new(),
            avatar_file_refs: HashMap::new(),
            avatar_downloads_due: BTreeSet::new(),
            avatar_rescan: true,
            completed_downloads: VecDeque::new(),
            downloads_panel_open: false,
            download_extras: HashMap::new(),
            search: SearchState::default(),
            chat_search: ChatSearchState::default(),
            pinned_messages: HashMap::new(),
            unread_jump: None,
            history_calendar: None,
            date_jump: None,
            date_jump_pending: None,
            date_jump_note: None,
            chat_media_counts: HashMap::new(),
            shared_media: SharedMediaState::default(),
            stickers: StickerPanel::default(),
            emoji: EmojiPanel::default(),
            gifs: GifPanel::default(),
            bot_user_ids: HashSet::new(),
            bot_info: HashMap::new(),
            bot_start_params: HashMap::new(),
            similar_bots: HashMap::new(),
            profile_chat_lists: HashMap::new(),
            user_profile_photos: HashMap::new(),
            bot_games: HashMap::new(),
            game_scores: HashMap::new(),
            bot_commands: HashMap::new(),
            draft_dirty: HashSet::new(),
            draft_clears: Vec::new(),
            sponsored: HashMap::new(),
            sponsored_hidden: false,
            sponsored_report: None,
            sponsored_report_target: None,
            last_sponsored_report: None,
            my_user_id: None,
            map_thumbs: MapThumbs::default(),
            users: HashMap::new(),
            contacts: None,
            contacts_error: false,
            contacts_notice: None,
            user_full_infos: HashMap::new(),
            translate: TranslateState::default(),
            reply_keyboards: ReplyKeyboardState::default(),
            stories: StoriesState::new(),
            chat_export: None,
            poll_voters: HashMap::new(),
            poll_stats: HashMap::new(),
            inline_query: None,
            inline_bot_resolve: None,
            inline_bot_resolve_seq: 0,
            active_emoji_reactions: Vec::new(),
            open_info_panel: None,
            username_check: None,
            username_check_pending: None,
            profile_edit_error: None,
            diagnostics,
        }
    }
}
