//! Exact pins for this checkout. Recheck together; never refresh one layer alone.

/// crates.io `gpui-kit` version selected on 2026-09-17.
/// Research snapshot cited git `d604a2ace` as package 0.6.1; crates.io default
/// is now 0.6.1 (0.6.0 also exists). The whole UI family is this Kit release
/// (`gpui-pre` ^0.3.1, resolved in Cargo.lock).
pub const GPUI_KIT_VERSION: &str = "0.6.1";

/// Official TDLib git commit used as the schema/runtime baseline.
pub const TDLIB_GIT_COMMIT: &str = "c15d3f5a5de6e3ba5839822c451152e5e18bb700";

/// CMake `project(TDLib VERSION …)` at [`TDLIB_GIT_COMMIT`].
pub const TDLIB_CMAKE_VERSION: &str = "1.8.68";

/// Official `td/generate/scheme/td_api.tl` at [`TDLIB_GIT_COMMIT`].
/// SHA-256 of the **upstream** file (not of a locally truncated copy).
pub const TD_API_TL_SHA256: &str =
    "cea6311c8a4ba0c73460b4f632b1e2b771499b32cf531f7297ee315a5a83eae5";

/// Byte length of that official schema file.
pub const TD_API_TL_BYTES: usize = 1_191_756;

/// Raw GitHub URL for the official schema at [`TDLIB_GIT_COMMIT`].
pub const TD_API_TL_UPSTREAM_URL: &str = "https://raw.githubusercontent.com/tdlib/td/c15d3f5a5de6e3ba5839822c451152e5e18bb700/td/generate/scheme/td_api.tl";

/// Relative path of the vendored schema.
pub const TD_API_TL_PATH: &str = "schema/td_api.tl";

/// Schema constructors this crate must keep typed coverage for.
pub const REQUIRED_SCHEMA_CONSTRUCTORS: &[&str] = &[
    "error",
    "ok",
    "authorizationStateWaitTdlibParameters",
    "authorizationStateWaitPhoneNumber",
    "authorizationStateWaitPremiumPurchase",
    "authorizationStateWaitEmailAddress",
    "authorizationStateWaitEmailCode",
    "authorizationStateWaitCode",
    "authorizationStateWaitOtherDeviceConfirmation",
    "authorizationStateWaitRegistration",
    "authorizationStateWaitPassword",
    "authorizationStateReady",
    "authorizationStateLoggingOut",
    "authorizationStateClosing",
    "authorizationStateClosed",
    "updateAuthorizationState",
    "updateNewMessage",
    "updateMessageSendAcknowledged",
    "updateMessageSendSucceeded",
    "updateMessageSendFailed",
    "updateDeleteMessages",
    "updateChatPosition",
    "updateChatTitle",
    "updateChatLastMessage",
    "updateChatAddedToList",
    "updateChatRemovedFromList",
    "updateChatReadInbox",
    "updateChatReadOutbox",
    "updateConnectionState",
    "setTdlibParameters",
    "getAuthorizationState",
    "loadChats",
    "getChatHistory",
    "sendMessage",
    "sendMessageAlbum",
    "openChat",
    "closeChat",
    "viewMessages",
    "messageSourceChatHistory",
    "logOut",
    "close",
    "chatListMain",
    "chatPosition",
    "chatTypePrivate",
    "chatTypeBasicGroup",
    "chatTypeSupergroup",
    "chatTypeSecret",
    "messageText",
    "messagePhoto",
    "messageDocument",
    "messageSticker",
    "messageAnimation",
    "messageVideo",
    "messageVideoNote",
    "messageVoiceNote",
    "messageAudio",
    "audio",
    "minithumbnail",
    "videoNote",
    "video",
    "animation",
    "animations",
    "inputMessageAnimation",
    "inputAnimation",
    "getSavedAnimations",
    "updateSavedAnimations",
    "voiceNote",
    "sticker",
    "stickerFormatWebp",
    "stickerFormatTgs",
    "stickerFormatWebm",
    "stickerTypeRegular",
    "stickerFullTypeRegular",
    "thumbnailFormatWebp",
    "inputMessageSticker",
    "inputMessageVoiceNote",
    "inputVoiceNote",
    "inputSticker",
    "inputFileId",
    "inputThumbnail",
    "getInstalledStickerSets",
    "getStickerSet",
    "stickerSets",
    "stickerSet",
    "stickerSetInfo",
    "photo",
    "photoSize",
    "document",
    "file",
    "localFile",
    "remoteFile",
    "thumbnail",
    "updateFile",
    "downloadFile",
    "cancelDownloadFile",
    "inputMessageText",
    "inputMessagePhoto",
    "inputMessageDocument",
    "inputMessageVideo",
    "inputMessageVideoNote",
    "inputVideo",
    "inputVideoNote",
    "inputPhoto",
    "inputDocument",
    "inputFileLocal",
    "formattedText",
    "textEntity",
    "textEntityTypeUrl",
    "textEntityTypeTextUrl",
    "linkPreview",
    "linkPreviewTypeArticle",
    "linkPreviewTypePhoto",
    "searchChats",
    "searchMessages",
    "searchRecentlyFoundChats",
    "addRecentlyFoundChat",
    "searchChatMessages",
    "foundChatMessages",
    "messageTopicForum",
    "getForumTopics",
    "forumTopics",
    "forumTopic",
    "forumTopicInfo",
    "getSupergroup",
    "supergroup",
    "updateSupergroup",
    "chats",
    "foundMessages",
    "messageReplyToMessage",
    "inputMessageReplyToMessage",
    "textQuote",
    "inputTextQuote",
    "editMessageText",
    "editMessageCaption",
    "deleteMessages",
    "updateMessageContent",
    "forwardMessages",
    "messages",
    "messageForwardInfo",
    "messageOriginUser",
    "messageOriginHiddenUser",
    "messageOriginChat",
    "messageOriginChannel",
    "addMessageReaction",
    "removeMessageReaction",
    "updateMessageInteractionInfo",
    "messageInteractionInfo",
    "messageReactions",
    "messageReaction",
    "reactionTypeEmoji",
    "pinChatMessage",
    "unpinChatMessage",
    "updateMessageIsPinned",
    "setChatNotificationSettings",
    "chatNotificationSettings",
    "updateChatNotificationSettings",
    "addChatToList",
    "chatListArchive",
    "sendChatAction",
    "updateChatAction",
    "chatActionTyping",
    "chatActionCancel",
    "chatActionRecordingVoiceNote",
    "openMessageContent",
    "updateMessageContentOpened",
    "messageSenderUser",
];
